// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app logs',
  description: `
  Opens a real-time stream of detailed log events from the selected app and store. Use the \`--source\` argument to limit output to a particular log source, such as a Shopify Function or webhook topic. Use the \`sources\` subcommand to list available sources.
  The \`--json\` argument can be used to receive log entries as line-delimited JSON (JSONL). By piping the output to tools like \`jq\`, you can filter the output to specific information.
  \`\`\`
  shopify app logs --json
  \`\`\`
  `,
  overviewPreviewDescription: `Stream detailed logs for your Shopify app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app logs',
          code: './examples/app-logs.example.sh',
          language: 'bash',
        },
      ],
      title: 'app logs',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app logs` command:',
    type: 'applogs',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data